"""Quick smoke-test: export_to_docx_from_template."""
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

# ── 1. Create a fake "user template" with custom styling ─────────────
template_path = "test_template_doc.docx"
doc = Document()

# Custom page margins
for section in doc.sections:
    section.top_margin = Inches(1.5)
    section.bottom_margin = Inches(1.5)
    section.left_margin = Inches(1.25)
    section.right_margin = Inches(1.25)

# Customize the Normal style font
style = doc.styles["Normal"]
font = style.font
font.name = "Georgia"
font.size = Pt(12)
font.color.rgb = RGBColor(0x33, 0x33, 0x33)

# Customize Heading 1
h1 = doc.styles["Heading 1"]
h1.font.name = "Georgia"
h1.font.size = Pt(22)
h1.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

# Customize Heading 2
h2 = doc.styles["Heading 2"]
h2.font.name = "Georgia"
h2.font.size = Pt(16)
h2.font.color.rgb = RGBColor(0x2D, 0x2D, 0x5E)

# Add some placeholder text (will be cleared by our function)
doc.add_heading("Template Placeholder Title", level=1)
doc.add_paragraph("This text should be replaced by AI content.")
doc.add_heading("Section Placeholder", level=2)
doc.add_paragraph("More placeholder text here.")

doc.save(template_path)
print(f"Created template: {template_path}")

# ── 2. Run the template-aware export ─────────────────────────────────
from app.utils.export_utils import export_to_docx_from_template

ai_content = """# Analysis Report

## Executive Summary

This is the **executive summary** generated by the AI pipeline.

## Methodology

- Step one: data extraction
- Step two: structural analysis
- Step three: sentiment profiling

## Results

The analysis found **positive sentiment** across all test subjects.

## Conclusion

All objectives were met successfully.
"""

output_path = "outputs/test_template_output.docx"
export_to_docx_from_template(ai_content, template_path, output_path)
print(f"Exported to: {output_path}")

# ── 3. Verify the output has the template's styles ───────────────────
result = Document(output_path)

# Check page margins were preserved
section = result.sections[0]
print(f"Left margin: {section.left_margin.inches:.2f} in (expected 1.25)")
print(f"Top margin:  {section.top_margin.inches:.2f} in (expected 1.50)")

# Check the Normal style font was preserved
normal = result.styles["Normal"]
print(f"Normal font: {normal.font.name} (expected Georgia)")
print(f"Normal size: {normal.font.size.pt if normal.font.size else 'inherited'}pt (expected 12)")

# Check content was injected
texts = [p.text for p in result.paragraphs if p.text.strip()]
print(f"Paragraph count: {len(texts)}")
print(f"First paragraph: '{texts[0]}'")
assert "Template Placeholder" not in " ".join(texts), "ERROR: Placeholder text was NOT cleared!"
assert "executive summary" in " ".join(texts).lower(), "ERROR: AI content was NOT injected!"
print("\n✅ All checks passed! Template styles preserved + AI content injected.")
